### ISSUE TITLE
Creating item from tutorial fails

### ISSUE THREAD

**Issue by anhilde** [FabricMC/fabric-docs#179]
Hello, I have set up a seemingly working development environment using IntelliJ and can start and debug a client/server. I manage to log output to the console and set breakpoints. I now try to create my first own item based on this description: https://docs.fabricmc.net/develop/items/first-item

I changed the Id, build the project and start the server. A log message I output in onInitialize in the main.mypackage.Test class is output in the server console. The Item that is created however, does not appear in the items list in the game. There is also no visible error in the server log. How would I best investigate where the problem lies?

**Comment by anhilde** [comment]
Problem partially soved. The item appears if I run the minecraft client. From the description this is not clear. I assumed I change the server and then connected to the modified server from an  unmodified client. Perhaps this is clear to seasoned minecraft folks, to me as beginner it is absolutely not. Could a suitable hint be added to the tutorial?

**Comment by LordEnder-Kitty** [comment]
Running the client and making a singleplayer world is all you need to do. You should never have to run the server unless you're making a specifically server only mod or you need to debug something in your mod. Running the client in IntelliJ is pretty much just like running the regular game. Running the server from IntelliJ is like hosting a whole, proper server on your machine. 

Does that help clear things up?

**Comment by winderine** [comment]
anhilde, you got a lot farther than I did. From having to import all of the minecraft things, which at least IntelliJ recognized, to not knowing what to do with "FabricDocsReference.MOD_ID" (I assume I'm supposed to change MOD_ID to my mod id? But FabricDocsReference remains an undeclared symbol...)

And for that matter it would be super useful to change "You can put this method in a class called ModItems (or whatever you want to name the class)." to something like "You can create a new class file to hold this method, and call it ModItems (or whatever you want to name the class)." just to remind those of us who haven't read the beginning chapter of a programming book in 5 years how to add classes to a multi-class project, because apparently it was such an obvious thing to find that two people had to quote a textbook at me when I asked for help in the discord. 

No, you know what would be more helpful, is having a copy of the working source code of the tutorial to cross-reference. This tutorial might be helpful to reference for people who already know how to do everything, but I've been at it for over two hours now and I still can't get the *first run* to *run*, and I'm not even a _complete_ newbie to programming, just a little inexperienced in java.

**Comment by LordEnder-Kitty** [comment]
If you go to [reference/latest](https://github.com/FabricMC/fabric-docs/tree/main/reference/latest) in this repository, you can see all the working code for pretty much everything shown in the tutorials.

**Comment by its-miroma** [comment]
To summarize, the two changes that this issue asks for are:

- [x] Clarify that running the server alone is not enough, the client is needed
- [x] Remind the reader that a full working mod is available in <https://github.com/FabricMC/fabric-docs/tree/main/reference/latest>

Is this correct?
