### ISSUE TITLE
meat method does not exist?

### ISSUE THREAD

**Issue by pypro485** [FabricMC/fabric-docs#186]
The docs say that a meat method for food exists but i cant find it am i doing something wrong or is this misinformation

**Comment by Linguardium** [comment]
it seems that this was copied over from the 1.20.4 docs and not updated. there is no meat method. you add the item to the meats item tag, preferably with datagen

**Comment by haykam821** [comment]
The following line needs to be changed as meat is based off of the `minecraft:meat` item tag rather than a field on the food component:

https://github.com/FabricMC/fabric-docs/blob/16248bc57a76e86d19e225d83541f6c3d393ae28/develop/items/food.md#L34

The `FoodComponent.Builder#usingConvertsTo` method was also introduced but is not mentioned on this page.

**Comment by pypro485** [comment]
how would i use "usingConvertsTo"?
