### ISSUE TITLE
Developer Guides: SoundInstances

### ISSUE THREAD

**Issue by IMB11** [FabricMC/fabric-docs#70]
This would fit well into the `Sounds` section being added by #68

**Comment by JR1811** [comment]
I can continue the sound pages category, which I have created already, if needed!

Things like...

-  Moving sound instances
- Dynamic volume and pitch changes
- Fading Transitions
- *(maybe even the networking part?)*

... should be pretty interesting, I guess.

I had used them a lot in my last [ModFest entry](https://github.com/JR1811/Boatism/tree/master/src/main/java/net/shirojr/boatism/sound/), so I think I can get started if it hasn't changed too much since 1.20.4

**Comment by JR1811** [comment]
Also, to explain and give examples to the dynamic part, maybe BlockEntities (#35) could be used in combination there.

**Comment by JR1811** [comment]
started working on the SoundInstance page
https://github.com/JR1811/fabric-docs/tree/dynamic-sound
